### PR TITLE
Slack webhooks

### PR DESCRIPTION
**Pull request by an1zhegorodov**
Besides fixing the issue with `SlackHandler`, also made message formatting consistent with previous version. However, we may consider changing it, as long as it duplicates information like context and extra in case they are included in attachment.

### CODE REVIEW

**Comment by an1zhegorodov** [comment]
@hkdobrev Sure. BTW, I tried both `SlackHandler` and `SlackWebhookHandler`. It works. Would also be nice to test `SlackBotHandler`.

**Comment by hkdobrev** [comment]
@an1zhegorodov Could you elaborate more on your second commit? Why do you need `getFormatter()` at all? Why do you say
> Make message formatting behaviour same as previous version

I couldn't find `getFormatter()` there before.

Why you set the formatter on the `SlackRecord` object when getting the formatter as well?

Thanks!

**Comment by an1zhegorodov** [comment]
@hkdobrev Sorry for not providing enough information about it.

The thing is that in [AbstractProcessingHandler::handle](https://github.com/an1zhegorodov/monolog/blob/6be4b80cdf58040b4b11ab551f71010fe3045535/src/Monolog/Handler/AbstractProcessingHandler.php#L35) there is a call to [AbstractHandler::getFormatter](https://github.com/an1zhegorodov/monolog/blob/6be4b80cdf58040b4b11ab551f71010fe3045535/src/Monolog/Handler/AbstractHandler.php#L112), which in turn sets current formatter to the default one if it has not been provided before. When this is the case, we need to provide that formatter to `SlackRecord` object, otherwise `$record['message']` will not be formatted because of [this condition](https://github.com/an1zhegorodov/monolog/blob/6be4b80cdf58040b4b11ab551f71010fe3045535/src/Monolog/Handler/Slack/SlackRecord.php#L109) in `SlackRecord`.

Ehh, sounds a bit confusing, let me know if you get it.

**Comment by hkdobrev** [comment]
@an1zhegorodov Thanks for the explanation! I didn't spend enough time on that before and your comment made it all clear!

**Pull request merged**
